### ISSUE TITLE
Not working in fresh CRA with TS project

### ISSUE THREAD

**Issue by ugened47** [agentcooper/react-pdf-highlighter#137]
Trying to add this amazing package to CRA with the TS template app.

Added `work-loader@^2.0.0`

`import PDFWorker from "worker-loader!pdfjs-dist/lib/pdf.worker";`
`setPdfWorker(PDFWorker);`

Tried copy files from existing example.

Getting next error:

```
./node_modules/pdfjs-dist/lib/display/annotation_layer.js 365:34
Module parse failed: Unexpected token (365:34)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|       link[jsName] = () => {
>         this.linkService.eventBus?.dispatch("dispatcheventinsandbox", {
|           source: this,
|           detail: {
```

Tried to follow [https://stackoverflow.com/a/63962030/5547079](https://stackoverflow.com/a/63962030/5547079)

And now having next errors:

```
./node_modules/pdfjs-dist/build/pdf.js 2407:53
Module parse failed: Unexpected token (2407:53)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                 intent: renderingIntent,
|                 renderInteractiveForms: renderInteractiveForms === true,
>                 annotationStorage: annotationStorage?.getAll() || null
|               });
|             }
```

Is there a workaround to get rid of all these errors?

Thank you guys in advance.

**Comment by agentcooper** [comment]
Could you please try version `4.0.0`? I've released it today. Feel free to reopen if needed.

**Comment by igorbpf** [comment]
> Could you please try version `4.0.0`? I've released it today. Feel free to reopen if needed.

I'm afraid it is still not working. Having the same issue with version 4.0.0

**Comment by agentcooper** [comment]
@igorbpf can you please provide a test repository with this setup?

**Comment by igorbpf** [comment]
> @igorbpf can you please provide a test repository with this setup?

Sorry for the late response, mate! I've been quite busy!

https://github.com/igorbpf/pdf-highlight

**Comment by nikhilag** [comment]
@agentcooper I am facing the same issue as well on a windows machine. Can this issue be reopened?
